import type { PlatformTab, PlatformData } from './types';

export const platformsData: Record<PlatformTab, PlatformData> = {
    web: {
        id: 'web',
        icon: '🖥️',
        name: 'Web Management Panel',
        shortLabel: 'Web Panel',
        tagline: 'Super Admin, Store Operations, Counter POS & Inventory',
        color: '#38BDF8',
        accentGlow: 'rgba(56, 189, 248, 0.2)',
        images: [
            {
                title: 'Store Command Center & POS Billing Terminal',
                subtitle: 'Operational Terminal, Live Queue & TV Kiosk Display',
                image: '/assets/products/grocery-mart/Screenshot 2026-09-26 182031.png',
                desc: 'Centralized store operations terminal for Sahil Grocery Shop (Sector 62, Noida). Unifies counter POS billing, active orders queue, TV kiosk screen mode, daily revenue metrics (₹5,98,900), and 99.8% SLA dispatch monitoring.',
                badges: ['Command Center', 'POS Billing', 'Orders Queue', 'TV Kiosk', '99.8% SLA'],
                specs: [
                    { label: 'Store Location', value: 'Sahil Grocery Shop (Sector 62, Noida)' },
                    { label: 'Daily Revenue', value: '₹5,98,900.00' },
                    { label: 'Orders Queue', value: 'Active Live Dispatch & Counter Queue' },
                    { label: 'Display Modes', value: 'POS Terminal • TV Kiosk Mode • Rider Counter' },
                    { label: 'SLA Adherence', value: '99.8% Sub-15 Min Dispatch SLA' },
                ],
            },
            {
                title: 'Real-Time Store Analytics & Staff KPI Matrix',
                subtitle: 'Margin Velocity, Staff Handling Speeds & Associate Radar',
                image: '/assets/products/grocery-mart/Screenshot 2026-09-26 182946.png',
                desc: 'Granular retail telemetry tracking average cart size (₹482), gross margins (18.4%), staff item handling speeds, replenishment alerts, and associate performance radar.',
                badges: ['Analytics Engine', 'Gross Margin (18.4%)', 'Cart Size (₹482)', 'Staff Radar', 'Velocity KPI'],
                specs: [
                    { label: 'Average Cart Size', value: '₹482.00 per Customer Order' },
                    { label: 'Gross Margin', value: '18.4% Real-Time Margin' },
                    { label: 'Staff Handling Speed', value: 'Sub-90s Item Pick & Pack Velocity' },
                    { label: 'Associate Radar', value: 'Accuracy, Speed, Punctuality & Attendance' },
                    { label: 'Replenishment', value: 'Automated Dark-Store Stock Depletion Signals' },
                ],
            },
        ],
        videos: [
            {
                id: 'command-ops',
                title: 'Store Operations & Command Center Walkthrough',
                duration: '01:56',
                badge: '🖥️ Command Center & Queue',
                src: '/assets/products/grocery-mart/WhatsApp Video 2026-09-25 at 6.05.05 PM.mp4',
                poster: '/assets/products/grocery-mart/Screenshot 2026-09-26 182031.png',
                desc: 'Comprehensive walkthrough of the operational terminal, active orders queue, TV kiosk screen mode, and live store dispatch SLA.',
            },
            {
                id: 'pos-checkout',
                title: 'High-Speed POS Counter Checkout Flow',
                duration: '00:26',
                badge: '⚡ POS Counter & Rapid Billing',
                src: '/assets/products/grocery-mart/WhatsApp Video 2026-09-25 at 6.05.13 PM.mp4',
                poster: '/assets/products/grocery-mart/Screenshot 2026-09-26 182031.png',
                desc: 'Real-time billing counter flow demonstrating barcode SKU scanning, instant item tally, and receipt generation.',
            },
            {
                id: 'analytics-kpi',
                title: 'Store Analytics & Staff Efficiency Radar',
                duration: '01:10',
                badge: '📊 Telemetry & Staff KPIs',
                src: '/assets/products/grocery-mart/WhatsApp Video 2026-09-25 at 6.05.14 PM.mp4',
                poster: '/assets/products/grocery-mart/Screenshot 2026-09-26 182946.png',
                desc: 'Detailed live store analytics walkthrough showcasing average cart metrics, gross margin tracking, and staff associate efficiency radar.',
            },
        ],
    },
    customer: {
        id: 'customer',
        icon: '🛒',
        name: 'Customer Mobile App',
        shortLabel: 'User App',
        tagline: 'High-Conversion Hyperlocal 10-15 Min Delivery PDP & Checkout',
        color: '#10B981',
        accentGlow: 'rgba(16, 185, 129, 0.2)',
        images: [
            {
                title: 'Customer Mobile App Storefront & Product PDP',
                subtitle: 'React Native (v0.86) & Expo SDK 57 Storefront',
                image: '/assets/products/grocery-mart/image.png',
                desc: 'Engineered for maximum retail conversion with instant pack-size variant switching, live delivery ETA calculation (sub-15 mins), transparent per-unit pricing, and one-tap dynamic cart quantity stepper.',
                badges: ['React Native', 'Expo SDK 57', '10-15 Min ETA', 'Dynamic Stepper', 'Vegetarian Filter'],
                specs: [
                    { label: 'Technology', value: 'React Native • Expo SDK 57 • Reanimated' },
                    { label: 'Delivery ETA', value: '10-15 Mins Hyperlocal Dispatch' },
                    { label: 'Pack Selection', value: 'Instant Variant Switcher (500ml / 1L / Combos)' },
                    { label: 'Cart UX', value: 'Sticky Bottom Stepper with Instant Haptics' },
                    { label: 'Dietary Markers', value: '100% Vegetarian & Nutrition Badges' },
                ],
            },
        ],
        videos: [
            {
                id: 'customer-app-walkthrough',
                title: 'Customer Mobile App Walkthrough & Hyperlocal Experience',
                duration: '01:28',
                badge: '🛒 Customer App Live Demo',
                src: '/assets/products/grocery-mart/WhatsApp Video 2026-09-25 at 6.05.15 PM.mp4',
                poster: '/assets/products/grocery-mart/image.png',
                desc: 'Full walkthrough of the customer mobile storefront, sub-15 minute grocery ordering, variant selection, and seamless checkout experience.',
            },
        ],
    },
    delivery: {
        id: 'delivery',
        icon: '🛵',
        name: 'Delivery & Picker App',
        shortLabel: 'Delivery App',
        tagline: 'Dark-Store Warehouse Bin Navigation & Continuous Barcode Scanning',
        color: '#F59E0B',
        accentGlow: 'rgba(245, 158, 11, 0.2)',
        images: [
            {
                title: 'Delivery Partner & Dark-Store Picker App',
                subtitle: 'Aisle/Rack Bin Navigation & Camera Barcode Scanner',
                image: '/assets/products/grocery-mart/WhatsApp Image 2026-09-27 at 1.42.06 AM.jpeg',
                desc: 'High-contrast UI engineered for warehouse pickers and delivery riders. Guides associates to exact Aisle, Rack, and Shelf coordinates, enforces FEFO expiry validation, and prevents packing errors via continuous camera barcode scanning.',
                badges: ['Warehouse Bin Nav', 'FEFO Expiry Check', 'Continuous Barcode', 'Cold Room Alerts', 'Rider Routing'],
                specs: [
                    { label: 'Warehouse Nav', value: 'Aisle 04 • Rack R-B02 • Shelf 2 Coordinates' },
                    { label: 'Barcode Engine', value: 'Camera Continuous Scanner & SKU Validation' },
                    { label: 'Batch Compliance', value: '100% Mandatory FEFO Expiry Inspection' },
                    { label: 'Handling Flags', value: 'Chilled Storage (<4°C) & Fragile Pouch Alerts' },
                    { label: 'Courier Portal', value: 'One-Tap Rider Pickup & GPS Route Optimization' },
                ],
            },
        ],
        videos: [],
    },
};
